### ISSUE TITLE
Automatic payment disbursement

### ISSUE THREAD

**Issue by drewgash** [icrackthecode/MPESA-API#1]
Hi Charles,

Let me begin by saying I love when someone simplifies something previously complicated (for no particularly good reason). Great work! I was wondering if you've looked into the API's "automatic payment disbursement" feature? I think we can both agree that's what makes this API extra special.

**Comment by icrackthecode** [comment]
Thanks. Simplicity is always the key.
I agree with you the automatic payment disbursement feature is quite a great feature
