### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ronniengoda** [icrackthecode/MPESA-API#5]
When i run the scripton my local machine i get this error after entering the amount and phone number and pressing the pay button

Warning: curl_errno(): supplied resource is not a valid cURL handle resource in C:\xampp\htdocs\MPESA\requestcheckout.php on line 27
To complete this transaction, enter your Bonga PIN on your handset. if you don't have one dial *126*5# for instructions
Warning: curl_errno(): supplied resource is not a valid cURL handle resource in C:\xampp\htdocs\MPESA\processcheckout.php on line 20

**Comment by godfreymakori** [comment]
@ronniengoda You might what to try out the new MPESA API. MPESA might deprecate the USSD push pop-up since the new MPESA utilize's a push through the sim toolkit. Users in-turn enter their MPESA pin and not bonga pin.

**Comment by ronniengoda** [comment]
Thanks alot so how do i go about the new MPESA API?? any project you have
done?...i will highly appreciate

**Comment by godfreymakori** [comment]
Yeah I have done a couple, you'll ofcourse need an MPESA paybill and access the MPESA portal - the one that requires a certificate and also you'll need to register at https://developer.safaricom.co.ke/login-register

Further details are available at https://developer.safaricom.co.ke/docs#authentication

You can email me at godfreykori@gmail.com for direct assistance

**Comment by icrackthecode** [comment]
Hey Ronnie you could probably try out the new api. looks like the request is invalid. Haven't used it in a while but systems that had implemented this are still working fine.
